<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: {{ .File.Name }}

namespace {{ .File | phpNamespace }};

/**
 *{{ .Service | protoComment .File | splitList "\n" | join "\n *" }}
 *
 * Generated from protobuf service <code>{{ .File.Package }}.{{ .Service.Name }}</code>
 */
interface {{ .Service | phpServiceName .File }}
{
{{- range $method := .Service.Method }}
{{- $inputType := $method.InputType | phpMessageName }}
    /**
     *{{ $method | protoComment $.File $.Service | splitList "\n" | join "\n     *" }}
     *
     * Generated from protobuf method <code>{{ $.File.Package }}.{{ $.Service.Name }}/{{ $method.Name }}</code>
     *
     * @param array $ctx
     * @param {{ $inputType }} $req
     *
     * @return {{ $method.OutputType | phpMessageName }}
     */
    public function {{ $method.Name }}(array $ctx, {{ $inputType }} $req);
{{ end -}}
}
