<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!

namespace Twitch\Twirp\Example;

use Http\Discovery\MessageFactoryDiscovery;
use Http\Discovery\StreamFactoryDiscovery;
use Http\Message\MessageFactory;
use Http\Message\StreamFactory;
use Psr\Http\Message\ServerRequestInterface;
use Twirp\Context;
use Twirp\RequestHandler;

/**
 * Server can be used to collect service server implementations and serve them in one.
 */
final class Server implements RequestHandler
{
    use Protocol;

    /**
     * @var RequestHandler[]
     */
    private $handlers = [];

    /**
     * @var MessageFactory
     */
    private $messageFactory;

    /**
     * @var StreamFactory
     */
    private $streamFactory;

    /**
     * @param MessageFactory|null $messageFactory
     * @param StreamFactory|null  $streamFactory
     */
    public function __construct(
        MessageFactory $messageFactory = null,
        StreamFactory $streamFactory = null
    )
    {
        if ($messageFactory === null) {
            $messageFactory = MessageFactoryDiscovery::find();
        }

        if ($streamFactory === null) {
            $streamFactory = StreamFactoryDiscovery::find();
        }

        $this->messageFactory = $messageFactory;
        $this->streamFactory = $streamFactory;
    }

    /**
     * Registers a server instance for a prefix.
     *
     * @param string         $prefix
     * @param RequestHandler $server
     */
    public function registerServer($prefix, RequestHandler $server)
    {
        $this->handlers[$prefix] = $server;
    }

    /**
     * {@inheritdoc}
     */
    public function handle(ServerRequestInterface $req)
    {
        foreach ($this->handlers as $prefix => $handler) {
            if (strpos($req->getUri()->getPath(), $prefix) == 0) {
                return $handler->handle($req);
            }
        }

        $msg = sprintf('no handler for path %q', $req->getUri()->getPath());

        return $this->writeError($ctx, Error::badRoute($msg, $req->getMethod(), $req->getUri()->getPath()));
    }
}
