<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: {{ .File.Name }}

namespace {{ .File | phpNamespace }};

use Http\Client\HttpClient;
use Http\Message\MessageFactory;
use Http\Message\StreamFactory;
use Psr\Http\Message\UriInterface;
use Twirp\Context;
use Twirp\Error;

/**
 * A Protobuf client that implements the {{ .Service | phpServiceName }} interface.
 * It communicates using Protobuf and can be configured with a custom HTTP Client.
 *
 * Generated from protobuf service <code>{{ .File.Package }}.{{ .Service.Name }}</code>
 */
final class {{ .Service | phpServiceName }}Client extends TwirpClient implements {{ .Service | phpServiceName }}
{
    /**
     * @var UriInterface
     */
    private $addr;

    /**
     * @param string              $addr
     * @param HttpClient|null     $httpClient
     * @param MessageFactory|null $messageFactory
     * @param StreamFactory|null  $streamFactory
     */
    public function __construct(
        $addr,
        HttpClient $httpClient = null,
        MessageFactory $messageFactory = null,
        StreamFactory $streamFactory = null
    ) {
        parent::__construct($httpClient, $messageFactory, $streamFactory);

        $this->addr = $this->urlBase($addr);
    }
{{ range $method := .Service.Method }}
{{- $inputType := $method.InputType | trimPrefix (printf ".%s." ($.File.Package | trim)) | phpFqn }}
    /**
     * {@inheritdoc}
     *
     * @throws Error
     */
    public function {{ $method.Name }}(array $ctx, {{ $inputType }} $in)
    {
        $ctx = Context::withPackageName($ctx, '{{ $.File.Package }}');
        $ctx = Context::withServiceName($ctx, '{{ $.Service.Name }}');
        $ctx = Context::withMethodName($ctx, '{{ $method.Name }}');

        $out = new {{ $method.OutputType | protoRelativeToPackage $.File | phpFqn }}();

        $url = (string)$this->addr->withPath('/twirp/{{ $.File.Package }}.{{ $.Service.Name }}/{{ $method.Name }}');

        $this->doProtobufRequest($ctx, $url, $in, $out);

        return $out;
    }
{{ end -}}
}
