<?php
# Generated by the protocol buffer compiler (protoc-gen-twirp_php {{ .Version }}).  DO NOT EDIT!
# source: {{ .File.Name }}

declare(strict_types=1);

namespace {{ .File | phpNamespace }};

/**
 *{{ .Service | protoComment .File | splitList "\n" | join "\n *" }}
 *
 * Generated from protobuf service <code>{{ .Service | protoFullName .File }}</code>
 */
interface {{ .Service | phpServiceName .File }}
{
{{- range $method := .Service.Method }}
{{- $inputType := $method.InputType | phpMessageName }}
    /**
     *{{ $method | protoComment $.File $.Service | splitList "\n" | join "\n     *" }}
     *
     * Generated from protobuf method <code>{{ $method | protoFullName $.File $.Service }}</code>
     *
     * @throws \Twirp\Error
     */
    public function {{ $method.Name }}(array $ctx, {{ $inputType }} $req): {{ $method.OutputType | phpMessageName }};
{{ end -}}
}
