<?php
# Generated by the protocol buffer compiler (protoc-gen-twirp_php {{ .Version }}).  DO NOT EDIT!
# source: {{ .File.Name }}

namespace {{ .File | phpNamespace }};

use Twirp\Error;

/**
 *{{ .Service | protoComment .File | splitList "\n" | join "\n *" }}
 *
 * Generated from protobuf service <code>{{ .Service | protoFullName .File }}</code>
 */
interface {{ .Service | phpServiceName .File }}
{
{{- range $method := .Service.Method }}
{{- $inputType := $method.InputType | phpMessageName }}
    /**
     *{{ $method | protoComment $.File $.Service | splitList "\n" | join "\n     *" }}
     *
     * Generated from protobuf method <code>{{ $method | protoFullName $.File $.Service }}</code>
     *
     * @param array $ctx
     * @param {{ $inputType }} $req
     *
     * @return {{ $method.OutputType | phpMessageName }}
     *
     * @throws Error
     */
    public function {{ $method.Name }}(array $ctx, {{ $inputType }} $req);
{{ end -}}
}
